### ISSUE TITLE
Remove support for Emoji One due to new licensing restrictions

### ISSUE THREAD

**Issue by TheLastProject** [Telegram-FOSS-Team/Telegram-FOSS#145]
Unfortunately, Emoji One decided to change their licensing, meaning that Free Software projects are now forced to stay with an outdated emoji set that never updates. It is probably no longer worth supporting Emoji One, especially with alternatives like Google Noto and Twemoji which are still under Free licenses and updated.

See https://www.emojione.com/blog/emojione-30-new-licensing-explained and https://github.com/Ranks/emojione/issues/488 for more information.

**Comment by Crissov** [comment]
[Emojitwo](https://github.com/EmojiTwo/emojitwo/)  shall be kept up-to-date, although we're still looking for designers willing to contribute under CC-BY-4.0.

**Comment by thermatk** [comment]
The ones currently in use can't change their license, so no need to REMOVE
The next time I'll just generate plain Twemoji which was a fallback currently due to E1 not being a full set anyway
Or emojitwo
Who knows when the next time will happen anyway

**Comment by Ecron** [comment]
@TheLastProject As far as I understand that post you linked, we can still use freely the EmojiOne set, as this project is classified as a "Digital App, chatroom". You can see the specific text in the screenshot below:

![captura de pantalla de 2017-06-29 14-14-01](https://user-images.githubusercontent.com/488803/27687163-0fd2c88e-5cd6-11e7-94f8-83d2d0b7954d.png)

So, no reason why we can't update to EmojiOne 3.0 and keep the attribution to them, in order to comply to their new licensing.

**Comment by TheLastProject** [comment]
@Ecron Because, as far as I'm aware, the point of this project is to replace the non-Open Source parts of the Telegram client with parts that are Open Source, which EmojiOne no longer is?

**Comment by Ecron** [comment]
Mmmmm that's true, indeed. Can't argue against that, but anyway EmojiOne is providing a Free License in a way that this project can still use that set of emoji. I know, they're no longer Open Source. But they're free. But they're not OS... Mmmm tricky 🤔 

If we stick to the pure concept of FOSS, I guess we should stick to the version 2 of the emoji. But maybe the free license give us some sort of liberty to use version 3 of EmojiOne. Yes, we don't have the source SVG files, but we're complying to the license they provide, right?

IDK, I just was happy with EmojiOne. Good artwork and a great free alternative. So sad.

**Comment by thermatk** [comment]
I'd say if the problem ever arises(we get some sources), it's easier to switch to twemoji and never look back

**Comment by moriel5** [comment]
I personally prefer the Noto emoji (although I almost never utilise emoji in the first place), why don't we use that in the first place, this is Android after all (and it could make the slightly lighter, by simply pointing to the system emoji font instaed of containing an emoji font).

**Comment by thermatk** [comment]
If you take a look at my latest approach, you'll see that twemoji is a lot easier to implement and maintain. It's the only 1:1 complete, so even now it's the version used as fallback for missing emojis in e1 and Noto

**Comment by moriel5** [comment]
In that case, I concede. :-)

**Comment by sp-1234** [comment]
Why not just drop the emoji support altogether? Are there people (among those who care about software freedom) who actually want them?

…Or just use whatever is present in the system.

**Comment by moriel5** [comment]
Some of my family uses them semi-regularly (although they may not count, seeing as they use whatever they have, with me as their "IT Manager", and I have a friend who is currently migrating to FOSS, and uses them on a daily basis.

Otherwise, I would not care very much about their existence (well, personally I don't), as I fully agree with that they should not have been added to the Unicode standard in the first place (especially with some of the more-than-questionable emoji).

**Comment by thermatk** [comment]
Once again, my approach is to provide a foss-friendly build while staying as close as possible to upstream. If anyone wants to try use the emoji from system again - fine with me, waiting for your Pull Request and we'll see whether it's easier and cooler

**Comment by jvschiavo** [comment]
Does twemoji support the latest Unicode 10 emojis? The latest Noto color emoji does, and they are more popular since they are used in Android, Chrome, and all Google products. The newest version will probably be available when Android O 8.0 stable gets released.
Also, I don't think using system emojis is a good idea in Android, since it is a mess, older devices don't receive newest emojis. It seems things are gonna change with Android O, but until there, providing the emojis with the app is the best option, as WhatsApp and Telegram do right now. Hangouts for example uses system emojis, and "older" devices (aka, with 7.1.2 or less) just see some error characters when a friend sends them an emoji they don't have.

**Comment by Crissov** [comment]
Twemoji does already support Unicode 10 and Emoji 5.

For Android, there is now [EmojiCompat](https://developer.android.com/topic/libraries/support-library/preview/emoji-compat.html).

**Comment by Peque** [comment]
Maybe related:

- [Telegram setting to use system Emoji (pull-request)](https://github.com/DrKLO/Telegram/pull/1447)
- [Android 8 / Noto Emoji update (issue)](https://github.com/googlei18n/noto-emoji/issues/141)

**Comment by thermatk** [comment]
https://github.com/DrKLO/Telegram/pull/1447 makes emoji pane slow for me, also it doesn't really use emojicompat, does it?

**Comment by thermatk** [comment]
Twemoji win
