### ISSUE TITLE
Permissions for voice calls

### ISSUE THREAD

**Issue by haho16** [Telegram-FOSS-Team/Telegram-FOSS#146]
Hey, 

 Thanks for keeping this fork active :). I have been looking at the permissions for Telegram since the last update, and it seems like there is an issue with permissions to receive and make voip calls (the new feature). Or at least this is my conclusion from the error I receive when getting into a call - "error initializing audio hardware" just after it connects and passes the "encryption" stage.  Do you know whether this could be a permission issue or something else? Thanks

I tried uninstalling and installing again, but permissions are the same and errors are the same. If there is any other debugging I could do, let me know. 

HTC Sensation
Cyanogen 10 / Android 4.1.2 / Kernel 3.0.53

**Comment by thermatk** [comment]
Hi!
It's an upstream issue :(
https://github.com/grishka/libtgvoip/issues/9

**Comment by haho16** [comment]
thanks @thermatk . I will be patient :)

**Comment by thermatk** [comment]
It is fixed in v4.0, let's see if we get the sources :)

**Comment by rbrito** [comment]
Thanks for the information that it may be fixed with an update to the new upstream. I was getting the "error initializing audio hardware" on my father's very low-specced Android phone. I will install version 4.0 from Google Play and see if this helps with the issue.

Otherwise, a patch may be created here and, depending on the acceptance by upstream, submit it.

Oh, BTW, super, duper thanks to @thermatk for maintaining this reliable, dependable fork of Telegram. It is highly, highly appreciated.

**Comment by omkarnathsingh** [comment]
This issue can be closed now!

**Comment by jvschiavo** [comment]
I think it can be closed now, right?

**Comment by haho16** [comment]
@jvschiavo and @omkarnathsingh, yest - tested on my HTC Sensation and this problem has disappeared :). Thanks to all involved in working on the update.

**Comment by haho16** [comment]
@jvschiavo and @omkarnathsingh, yest - tested on my HTC Sensation and this problem has disappeared :). Thanks to all involved in working on the update.
