### ISSUE TITLE
Upload 4.1.1 to F-Droid

### ISSUE THREAD

**Issue by sp-1234** [Telegram-FOSS-Team/Telegram-FOSS#162]
(I'm sorry if this is already being taken care of)
I see the merge happened about 20 hours ago, so maybe it's time for it to be present on F-Droid too.

**Comment by ildar** [comment]
should be automatic, see
https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/org.telegram.messenger.txt#L275

**Comment by thermatk** [comment]
https://gitlab.com/fdroid/fdroiddata/merge_requests/2375

**Comment by sp-1234** [comment]
However, it's still not available to end users. Also, https://gitlab.com/fdroid/fdroiddata/merge_requests/2375#note_35113305

**Comment by thermatk** [comment]
@sp-1234 come on, the server only ran once and the server code has changed, so all the apps had to attach a "b" because before a substring was enough
https://gitlab.com/fdroid/fdroiddata/commit/bd9ad4ccea448952be1a35663ae212092fd33473
at least research a bit before posting, you could've easily seen the metadata file has changed after the last build attempt 👍
