### ISSUE TITLE
Clarify Notifications.md

### ISSUE THREAD

**Issue by picsi** [Telegram-FOSS-Team/Telegram-FOSS#253]
Notifications.md is a really good idea, but as a layman I was a bit confused by the current wording. Let's improve it!

I propose we reword this

>Since we can't use Google's push messaging with Firebase in our FOSS app, we have no choice but to do the battery draining general app exclusion (which would be too much and draining more for no good), lose the ability to receive pushes about new messages altogether (getting pinged once in 15 minutes wouldn't be OK for a messenger, would it?) or show this annoying notification and keep everything as it were.

into this:

>Since we can't use Google's push messaging with Firebase in our FOSS app, we have three possibilities
>* Do the battery draining general app exclusion (which would be too much and draining more for no good), 
>* Lose the ability to receive pushes about new messages altogether (getting pinged once in 15 minutes wouldn't be OK for a messenger, would it?) 
>* Show this annoying notification and keep everything as it were.

It's also worth writing in the document that, despite Google's warnings, there is no noticeable difference in battery usage if you make an exception for Telegram.

**Comment by theel0ja** [comment]
I'd suggest you to open a PR.

**Comment by thermatk** [comment]
Added. If you have more ideas, open PR or issue again :)

**Comment by Bubu** [comment]
@GutHib I'll try some English explanation, not sure how successful I'll be...

The notification is shown such that the Android OS considers Telegram as having a user visible (foreground) activity. There are different rules for foreground apps than there are for background ones. What was currently always allowed in the background is now only possible when the app is in the foreground (= showing a notification). That's why nothing has changed as long as Telegram keeps showing the notification.

**Comment by GutHib** [comment]
Thanks for the explanation. So to that end, it is enough if Telegram shows a single notification when the phone starts up, or does it have to nag every X hours?

**Comment by thermatk** [comment]
It has to show constantly
