### ISSUE TITLE
5.13 Source Available, and "Reproducible Builds"

### ISSUE THREAD

**Issue by moriel5** [Telegram-FOSS-Team/Telegram-FOSS#376]
As mentioned in the title, version 5.13's source code had been released to the public.

What is interesting is Telegram's announcement about "reproducible builds".
Could this mean that Telegram will finally stick to their claims of being open-source? If so, this should be a relief to many (though noGAPPs users will still need the FOSS fork for things such as map previews).

**Comment by PoliNetwork** [comment]
> Could this mean that Telegram will finally stick to their claims of being open-source?

Yes. https://t.me/tgbetachat/200141 https://t.me/tgbetachat/198962

> If so, this should be a relief to many

Yes, it is

> though noGAPPs users will still need the FOSS fork for things such as map previews

Yes, I hope this fork will be kept mantained

**Comment by ArmeF97** [comment]
> Yes. https://t.me/tgbetachat/200141 https://t.me/tgbetachat/198962

🥳 good!

**Comment by Lesik** [comment]
> though noGAPPs users will still need the FOSS fork for things such as map previews

> Yes, I hope this fork will be kept mantained

...and also the stripped binary blobs, removed telemetry and tracking, up-to-date SSL and other libraries. These are way more substantial to your freedom. This project here is far from obsolete just because upstream decided to release source code more often. Also remember that F-Droid will never allow the official source to be built into an apk for distribution via their store.

**Comment by moriel5** [comment]
@Lesik, thanks.
Though I was talking about user-facing features, what you had said is certainly correct.

**Comment by ralmcruz** [comment]
Anybody knows for sure if it will be kept mantained?

**Comment by thermatk** [comment]
I don't know who knows such things for sure
have fun with v5.13.1 :+1:
