### ISSUE TITLE
Implement Plus Messenger Features

### ISSUE THREAD

**Issue by Z3ROGRAV1TYx** [Telegram-FOSS-Team/Telegram-FOSS#377]
Would highly appreciate a lot of the features Plus Messenger has. 
For one, they do not have an F-Droid release, secondly they have stated the following about source code in their Telegram Support group (Pinned):

> ### Source Code
The last version of the source code is available to limited parties like Telegram itself. Like Telegram does sometimes, Plus Messenger dev delays the release of the source code to avoid other third party devs to use the code of Telegram and Plus Messenger in his own benefit by adding ads and other things without even giving credit to the respective authors and claiming they are the official sources.
In the meantime you can look for the source code on:
Github: https://github.com/rafalense/Plus-Messenger
Gitlab[current]: https://gitlab.com/rafalense/plus-messenger

Now this is understandable, I know Telegram delays their source code (Which does aggravate me personally) but the Gitlab for Plus Messenger that is linked has not had a commit posted in 2 years, the only thing being the Readme which was updated 10 months ago. 
In my opinion, Telegram's app (Including this FOSS version) is severely lacking in feature set. This is where Plus Messenger came in, and is why so many users opted for it. Because it genuinely was great.
One of the biggest things for me was split tabs. (Ability to seperate (super)groups, direct messages, channels). I did see a ticket ( #257 ) for that opened on here, but hasn't been replied too since August. 
As well as the themeing options it provided. It also included many useability enhancements. 
The best way to show is to download it for yourself, and look under "Plus Settings". It's extremely customizable and feature rich. Most specifically the "General, Dialogs, Messages" categories. 

I would absolutely love to be able to switch to Telegram-FOSS..  but the lack of featureset in comparison to Plus Messenger is an absolute shame. Alongside them literally not having an F-Droid release. Plus Messenger is open source, and I think majority of these features can most likely be found on their GitLab, so I would assume it won't require a complete write up of everything? I may be wrong though. 

But I genuinely think maybe you guys should implement some of these features, it would bring more users to you guys. It would be a great move. 
I genuinely hope this gets considered, despite the amount of work it may take. I hope you guys truly understand my reasoning and don't just put this off as "oh just don't use our app then", because you guys are doing an AMAZING thing and I really hope I can swap to your app. But it's the same reason why I never used the original Telegram app and many others.. Plus Messenger has soooo many damn features. Once you get those options, to switch to something that has basically none of those features absolutely sucks.

**Comment by moriel5** [comment]
I agree that it would be nice for Telegram-FOSS to add these features, however they are out of it's scope, since Telegram-FOSS is meant to be a completely open-source version of Telegram, and as such, the only "extras", are merely drop-in replacements for features that cannot be used without Google's Play Services.

A good option would be to create a new client like Plus Messenger (minus their source release attitude), but using Telegram-FOSS as the base, rather than the official Telegram.

**Comment by Z3ROGRAV1TYx** [comment]
>A good option would be to create a new client like Plus Messenger (minus their source release attitude)

Understood, this would probably be the way to go.

**Comment by moriel5** [comment]
Agreed, though I additionally wish for someone (or me, once I know enough how to do it) to make the code more efficient, so as to allow the app to be much lighter, both size-wise and in terms of system resources required).

**Comment by anupritaisno1** [comment]
@Z3ROGRAV1TYx Honestly we don't care at all about features. Nobody is going to have the time to maintain any of it

Why not stop writing essays and actually show interest in maintaining here? Send your patches for features

**Comment by moriel5** [comment]
Essays? This was a perfectly legitimate request, with solid reasoning and background behind it.

Especially since @Z3ROGRAV1TYz already mentioned they lack the skills to implement features, and I had said that regardless, they would not be accepted, since that is not the point of Telegram-FOSS, however building such a client, forked from Telegram-FOSS, would be the proper thing to do.

**Comment by DI555** [comment]
btw, this is an issue, and the starter must writing about exact things ...;)
i saw only one, and this is about 'split tabs'/'separated tabs'...
yes we all want this stuff ;), and waiting for it !!!

**Comment by DI555** [comment]
but anyways it's imo duplicate...
https://github.com/Telegram-FOSS-Team/Telegram-FOSS/issues/298

**Comment by thermatk** [comment]
@moriel5 summed it up well, another fork would be the solution. 
someone making tabs might find exciting stuff in the tabs42 branch
https://github.com/Telegram-FOSS-Team/Telegram-FOSS/commits/tabs42

**Comment by opensource-compliance-gh** [comment]
**Record update, 2026-09-01**

The source situation quoted in the opening post has not changed since 2019, and the current binary shows why it matters. Confirmed facts only:

- Current Google Play release: Plus Messenger 12.10.1.0 (2026-08-29), 50M+ installs. Newest source the developer has ever published: v4.2.1.1 at gitlab.com/rafalense/plus-messenger, last code commit `1d961518` on 2017-09-13 (three commits total, no tags). Source requests on that tracker (its issues 20 and 22) have been open and unanswered since 2018.
- "Source code updated to vX" in every release note refers to rebasing onto upstream DrKLO/Telegram, not to publishing source. The developer's own repository has had no code commits since 2017.
- Decompiling the current release (base APK SHA-256 starting `d332a130`, signature-verified as the developer's own build) shows current upstream GPL code plus a proprietary `org.telegram.plus.ads` layer: an ad engine (`AdsController`) and Google Play billing (`BillingHelper`) that sells ad removal for EUR 5.99 to 99.99. That layer exists in no published source of any version. The app carries no in-app license text and no written offer for source.
- The pinned rules quoted above justify withholding source by the risk of others "adding ads" for "his own benefit". The developer introduced his own ads in October 2025 (t.me/plusmsgr/458).

GPLv2 section 3 requires each binary to be accompanied by complete corresponding source or a written offer. Neither exists on the Play listing, in the app, on plusmessenger.org, or in the repositories (checked and archived 2026-09-01). The upstream copyright holder (Telegram, dmca@telegram.org and abuse@telegram.org) and the FSF (license-violation@gnu.org) were notified on 2026-09-01.

Posting so the public record is current. Full evidence, hashes and archived copies are available on request.

Open Source Compliance

**Comment by vdbhb59** [comment]
@thermatk and any admins, please delete this comment from the bot above. The bot has come and posted on several forums. Just created account and posted this. Banned them. Reporting this as well.

**Comment by opensource-compliance-gh** [comment]
> [@thermatk](https://github.com/thermatk) and any admins, please delete this comment from the bot above. The bot has come and posted on several forums. Just created account and posted this. Banned them. Reporting this as well.

Not a bot, though I'll take that as a compliment on the formatting. A bot wouldn't have spent an evening running apksigner and reading nine years of a Spanish support group. It's one person and one account, made for this because I'd rather not post under my own name anywhere near that developer.

Everything in my comment links to something you can open yourself: the GitLab commit API, the APK and certificate hashes, the message IDs with their own timestamps. If a line is wrong, quote it and I'll fix it here.

You didn't quote a line. You say you banned me on the F-Droid forum; my account there is gone and the post never left the moderation queue. Now you're here asking the maintainers to delete this one too. That's a lot of effort to keep a commit history out of sight. What in it needs hiding?
