### ISSUE TITLE
Make contact discovery optional

### ISSUE THREAD

**Issue by Bubu** [Telegram-FOSS-Team/Telegram-FOSS#39]
As this is a privacy enhanced version of the upstream Telegram client making contact discovery optional would be an essential feature.
I realize contact discovery is a very useful feature but Telegram should respect user choice before sending any contact data to the server side.

This should probably a first run question and an later an option in the preferences.

I will try to look into it if I find the time.

**Comment by slp** [comment]
Sounds reasonable.

**Comment by aphirst** [comment]
Mmm, after reading [this article on "Telegram stalking"](https://oflisback.github.io/telegram-stalking/) it occurred to me that Telegram really ought have some additional measures to protect user privacy - somehow there needs to be some notion of approval or confirmation before users get added to contact lists, and also preferably (if possible, might be server-side issue) prevent even the leaking of online-status metadata.

In any case I'm interested to see whether anything in this regard does happen over here on Telegram-FOSS.

**Comment by abate** [comment]
:+1:

**Comment by Bubu** [comment]
@abate Easiest should be to install [Android Studio](https://developer.android.com/sdk/index.html) and the [Android NDK](https://developer.android.com/tools/sdk/ndk/index.html).
Android studio should take care of everything SDK-setup and emulator related.

Clone the git repository and import the project into android studio.
Change to the TMessageProj subdirectory and run `$ANDROID_NDK_HOME/ndk-build`.
Then run the project from Android studio.

**Comment by Bubu** [comment]
As an added note: When I was looking at this I encountered this Telegram API method: https://core.telegram.org/method/contacts.importContacts

I think it should be possible to clear all server site saved contacts of a user. But I did not yet get around to trying it out.

**Comment by Ecron** [comment]
The iOS version asks before importing contacts, but because the system NEEDS you to give access to them. Android doesn't asks for that permission, but I'd love the app would ask if I want to import my contacts or don't.

I'd make it this way: When I first log in, the app asks if I want to import my contacts. If I say yes, everything would go as it goes right now. If I say no, the app would disable its importing functions (because Telegram always checks for Contacts changes when you open it) and it would ask again when I next run the app. Why asking everytime I run the app? Because not importing the contacts kind if undermine Telegram's behaviour -- it works better with contacts imported.

**Comment by Roboe** [comment]
@Ecron Asking every time a user opens Telegram-FOSS is a bad experience, in my opinion. Should do with asking only the first time, an option in settings and a reminder on Contacts section, maybe.

**Comment by Ecron** [comment]
@Roboe Not every time a user OPENS Telegram-FOSS, but everytime a user RUNS the app (after forcing close, rebooting the phone, etc.).

But I understand your point, though.

**Comment by Allanitomwesh** [comment]
Android 6 does ask if you'll give permission to telegram to access contacts. Perhaps work using this, such that if someone says no, the app continues working as normal but with no contacts

**Comment by Ecron** [comment]
So it's a OS related bug, not a Telegram one. @Bubu I guess you can close this issue.

**Comment by abate** [comment]
For older versions of android you have to go deep in the settings menu to remove the authorization to access contacts. I'm still convinced that adding an option to telegram is the way to go.

**Comment by Ecron** [comment]
The thing is that older Android versions should have a way to prevent apps to access contacts, but they haven't. So, keeping in mind that the goal of this fork is to make Telegram a true FOSS app, should they add an option to achieve that functionality missing in the OS?

I believe it would be a great privacy feature, but I'm not sure if that's the goal of this fork.

**Comment by Allanitomwesh** [comment]
At the very least it would be best to look into making the app work even if they say no to giving the app contacts (because currently if you say no it doesn't work)

**Comment by Bilkow** [comment]
I'm using telegram from F-Droid and it actually works without giving my contacts (maybe because it uses my contacts from other platforms). Before I had android remember my decision to refuse access to my contacts it asked me everytime I ran it (after force-closing), which was a pain in the ass.
I'm with @Roboe, reminder in the contacts and option in settings. (for both contact access and contact importing)

**Comment by thermatk** [comment]
If you deny the request once, next time there will be the checkbox "never ask again"
I would say it is solved since the introduction of the runtime permissions.
@Bubu you can probably close this one as well :+1:

**Comment by Matttter** [comment]
Isn't that checkbox and the dialog from android rather than the app? I think that on older versions of android there would still be automatic contact discovery, with the permissions coming in an everything-or-nothing package.

**Comment by thermatk** [comment]
@Matttter true, I do forget that there are people below Android 6.0 :)
then it really makes sense to show a dialog

**Comment by thermatk** [comment]
[That's the function where the preference should be added](https://github.com/Telegram-FOSS-Team/Telegram-FOSS/blob/master/TMessagesProj/src/main/java/org/telegram/messenger/ContactsController.java#L1337)
But how should the initial default setting work? An additional dialog during setup with a checkbox or what? I have no idea :)
Just migrate to 6.0 :rofl:

**Comment by thermatk** [comment]
So, I've tried and this is extremely easy to do, right now. 
BUT this is a feature which requires that in the future it will be always implemented if ever done once. Users will expect that if they installed Telegram and it didn't tamper with contacts, a simple update from F-Droid won't revert this decision. This makes it unique, because the osmdroid location sharing feature, for instance, if can't be done quickly next time can just be disabled... 

I'd say on <6.0 use Privacy Guard, AppOps or Xposed XPrivacy, on 6.0+ just deny the permission two times and tick "never ask again". 
Until someone joins the development and can absolutely guarantee that he will maintain this feature, it's a wontfix

**Comment by yurkobb** [comment]
I have a few questions about this:

1. Is there even a way the user could disable this behavior *before* the app manages to upload all the contacts, especially on Android <6.0? I know there is a setting (`Settings > Privacy & Security > Data Settings`) that allows disabling it, but is it accessible in a way that allows disabling it from the start?
2. Does the app ask the permission for **uploading the contacts to the server** or just for **accessing the contacts**? These are quite different actions.

I am strongly in favor if Telegram-FOSS would consider simply changing the default value of the setting to avoid uploading all the user's contacts without explicit permission (and awareness) of the user. If the user changes the setting, I would consider that to be enough to qualify as consent.
