### ISSUE TITLE
[FR] Forward Without Quoting

### ISSUE THREAD

**Issue by seniorm0ment** [Telegram-FOSS-Team/Telegram-FOSS#405]
Feature I used a lot on Plus that I miss, essentially it forwards messages as if you posted them and just doesn't have the "Forwarded from x" text above.

**Comment by mbnoimi** [comment]
+1

**Comment by rustforfuture** [comment]
I can understand you want to honor copyright.

But this option really have many legit use cases.

Like for example i had a channel that wasn't nsfw but telegram banned it for our country number so i can't access even my forwarded (saved messages) from that app.

Probably just because that channel posted may be sone edgy picture and telegram cobsidered it as porn.

Although about 70 percent of its pictures was about nature and such.

Just like unsplash that has some annoying nsfw pics but have many legit pics.

If i forwarded and saved those messages without quote, at least my saved messages didn't also replaced with a message that this content isn't available because of nsfw.

Or in my country there isn't a way to buy some media, so i save them from channels that share them so i can use for my personal use (fair use) (because I can't buy them at all) but after they get caught in copyright of telegram, all my saved messages from that channel also get replaces with message that this is not available.

Please add this.

I want to get rid of non stable non foss telegram clients And also official obe because it uses gcm and appcenter sdks in it but i cant because of only two missing options.

One is this and another is option to have about 10 accounts added to client that is out of scope of this issue and i will comment in another issue for it or create a new one specific for it.


Thank you very much for this great app.

**Comment by Younes-L** [comment]
Good news, telegram are adding this feature to the beta version of **telegram for macos** client.
If a stable version is released then we can expect other official clients (such as tandroid which is the upstream of this fork) to also implement this feature.

**Comment by rustforfuture** [comment]
Thank you very much

**Comment by Jrchintu** [comment]
This is a good feature, it also provide privacy in many cases. Suppose when you want to hide to whome you were chatting to and still want to forward a message from that person to public group.

**Comment by Younes-L** [comment]
@Jrchintu  Already added by telegram and subsequently telegram-foss, some 6 months ago
https://telegram.org/blog/live-streams-forwarding-next-channel

**Comment by thermatk** [comment]
Great
