### ISSUE TITLE
No non debug apk files available 

### ISSUE THREAD

**Issue by randomhydrosol** [Telegram-FOSS-Team/Telegram-FOSS#446]
The current release build is a debuggable apk. There should be a separate build with debugging removed like fdroid builds

**Comment by DI555** [comment]
i would suggest the full analogue of f-droid's build - same app name and signature from f-droid's apk !!!
just to have possibility to skip to this one easily from f-droid's build !!!

**Comment by Enrico204** [comment]
F-Droid is signing the APK with their own key, so it's not possible to produce an APK with have the same signature.

You can still download the APK from this GitHub repo. Just delete the old Telegram-FOSS app before installing this one. And make sure to do the same when F-Droid publishes their update.

**Comment by rondevous** [comment]
There's a problem of different signature. F-droid signs the releases with its own key, and that will conflict with the signing key used to make a non-fdroid release available. A non-debug APK (not by F-droid) won't allow you to update an already installed Telegram if it was installed via F-droid.

Because of this problem, there probably won't be any non-debug release on github in the future.
Also, it is not possible to forge the sha256 RSA signature of an APK, and make it look like its from F-droid. (unless you figure out f-droid's private key, which would take a million years of cracking).

Please wait for F-droid to build and release an update :D
Telegram video calls are still in its alpha stage of dev, so there's really no need to hurry :smile:

**Comment by anupritaisno1** [comment]
Stop making up utter nonsense. The package name can very well be changed. A debug build has been marked as a release and shipped out, how is that not a problem?

**Comment by thermatk** [comment]
@anupritaisno1 What
Who marked what as release
Find this person!

**Comment by anupritaisno1** [comment]
You did

**Comment by Enrico204** [comment]
@anupritaisno1 you can still clone the repo, change the package name (if you wish), build the app and install it on your phone. I don't think that anyone will build a app only for you.

Or you can wait few more days for F-Droid release, like everyone else. It's all run by volunteers

**Comment by DI555** [comment]
Guyes, the key that lays on the main page of f-droid isn't enaugh to sing by this key ;) ?

**Comment by Enrico204** [comment]
No, that is the public key. A signature requires the private key

**Comment by DI555** [comment]
so, won't any chance to grab that private key for build with installation over f-droid's one?
ok, will wait f-droid's one than ;)!

**Comment by stefan-niedermann** [comment]
F-Droid release just arrived, so everybody chill out 😉

**Comment by thermatk** [comment]
This wrongly formulated issue causes confusion and is to be closed:

the beta builds are obviously labeled BETA and are debug builds. The release builds are built and signed by f-droid and are not debug builds. It has always been very clear
