### ISSUE TITLE
Is anyone going to mention how this fork is useless and unusable because of emojis?

### ISSUE THREAD

**Issue by Simon311** [Telegram-FOSS-Team/Telegram-FOSS#533]
Whatever you're using looks cringe and you know it

**Comment by stefan-niedermann** [comment]
Well, personally i am happy with the current state. Your statement looks a bit generic and implicates that this is the opinion of *everybody*.

> this fork is useless and unusable

If you are not happy with the decision made by the project you are welcome to show some engagement in the development or start your fork (it is open source after all) to bring in your wisdom. Otherwise i recommend you to show a little more respect to all the people who take care about a free and open source Telegram Android client in their free time for no reward.

Sit down a minute and think about what you just wrote. Much time and love has been spent by human beings.
While your opinion and wish might be relatable, your behavior will not make anyone interested in listening to you.

**Comment by thermatk** [comment]
What I don't see is any kind of suggestion 👻 twemoji continuously cover the biggest set of new emojis in every new standard quick enough, so it's an obvious choice

**Comment by Simon311** [comment]
The suggestion is to use Apple emoji until Apple actually starts making trouble.

**Comment by thermatk** [comment]
Would you be willing to set up a contract with a lawyer for me, pay the retainer and all subsequent costs? 😂 Just for me to know I can even consider this option
