### ISSUE TITLE
Periodic awakening without data connection

### ISSUE THREAD

**Issue by ioctl-user** [Telegram-FOSS-Team/Telegram-FOSS#546]
Seems, related to [this](https://github.com/Telegram-FOSS-Team/Telegram-FOSS/issues/59).

Telegram periodically wakes up even without WiFi and Mobile data connection. This increases power consumption in such mode.

Is it possible to use some kind of network availability notification instead of periodic alarm?

**Comment by proletarius101** [comment]
The alarm now is inexact, meaning it will wake up the device with other apps. So it shouldn't wake-up the device crazily.

As long as it costs little in each wakeup, it will be fine.

**Comment by ioctl-user** [comment]
> As long as it costs little in each wakeup, it will be fine.

This correct in a city environment.

However, while being outdoor or traveling, it's sane turning off mobile data and allow only SMS and phone calls to save battery. In this situation, Telegram increases power consumption significantly.

**Comment by proletarius101** [comment]
You are right. But even with network connectivity, Telegram is supposed to use <1% battery. So I guess that shouldn't be considered as “significantly”?

Currently, Telegram-FOSS consumes much more than expected, since each wake up is costly. That's potentially fixed by https://github.com/Telegram-FOSS-Team/Telegram-FOSS/commit/bd95f3718e08999e1f3d91e99afaae139f4dcbc1

**Comment by ioctl-user** [comment]
I have repeated tests with version 8.1.2 (2432). Telegram didn't wake up without data connection, which is unexpected. So, closing this issue.
