### ISSUE TITLE
Update src to 8.3

### ISSUE THREAD

**Issue by srhughes89** [Telegram-FOSS-Team/Telegram-FOSS#558]
Any idea when the src will get updated to Telegram 8.3?

Looking forward to the Protected Content for Groups and Channels.

**Comment by Younes-L** [comment]
> Any idea when the src will get updated to Telegram 8.3?
> 
> Looking forward to the Protected Content for Groups and Channels.

when maintainer has time && when upstream fix the recent bugs
first condition may be met this sunday, second condition unknown ETA
telegram 8.3 has added more bugs on top of 8.2.7 and did not fix any of the existing 8.2.7 bugs, it will be wiser to wait a little more for upstream to fix these new bugs (such as users unable to delete their own message in group chat, and admins/bots can't ban or block posting as anonymous channels)

8.3.2 binary has been released but 8.3.2 source code is pending, so that's one way to tell when upstream are done yet

**Comment by xerz-one** [comment]
You might as well want to update the ticket to 8.4.2 https://github.com/DrKLO/Telegram/commit/c1c2ebaf4690fd91c116d80db653289c9447ef7a

**Comment by srhughes89** [comment]
Accomplished. Thanks a lot!!!
