### ISSUE TITLE
8.4.2 suddenly inflated to 63mb?

### ISSUE THREAD

**Issue by fcore117** [Telegram-FOSS-Team/Telegram-FOSS#565]
Please separate Arm x64 back into separate apk again as Arm 64 is most dominant, conserves download size too.

**Comment by r4sas** [comment]
That's because this is single apk for all architectures. F-Droid have some limitations about building apk per every arch.

**Comment by fcore117** [comment]
Previously it worked very well. Now i just have to disable auto update and only update when on unlimited wifi.

**Comment by 2743ab2** [comment]
> Please separate Arm x64 back into separate apk again as Arm 64 is most dominant, conserves download size too.

agree!


> That's because this is single apk for all architectures. F-Droid have some limitations about building apk per every arch.

then let arm7 be assembled together with other architectures, and arm64 made separately!

**Comment by Younes-L** [comment]
> then let arm7 be assembled together with other architectures, and arm64 made separately!

The rationale behind this is that "modern" phones and devices have a lot more ram and storage than armv7 devices.
You think you want the insignificant performance benefits of an armv8 only build, think again, because users of armv7 device need their significant performance gains even more.

Also keep in mind that telegram themselves, with all their resources and full-time dev salaries, only provide a single fat universal build, no arch optimised builds.

**Comment by fcore117** [comment]
> > then let arm7 be assembled together with other architectures, and arm64 made separately!
> 
> The rationale behind this is that "modern" phones and devices have a lot more ram and storage than armv7 devices. You think you want the insignificant performance benefits of an armv8 only build, think again, because users of armv7 device need their significant performance gains even more.
> 
> Also keep in mind that telegram themselves, with all their resources and full-time dev salaries, only provide a single fat universal build, no arch optimised builds.

Ram and storage are big, but sadly cheaper data plan with prepaid have limited bandwidth, for now only solution is disable updating and update only on unlimited free wi-fi

**Comment by 2743ab2** [comment]
Okay, obviously there is a problem!
As explained above, this problem occurs on the side of the f-droid, which cannot host the release of an application of all architectures individually. And as you can see from the latest publications in the f-droid, only 2 applications can be published.
This forces us to argue about which architecture is worth publishing separately. We can argue for a long time, each side has its own arguments.
I propose to do it differently. The Telegram foss team can publish application releases here, as, for example, NekoX does, a separate application for each architecture. Then, who does not care about the "signature" of the f-droid, they will take the necessary * .apk here.

**Comment by thermatk** [comment]
Oh come on :rofl: 

The universal will always be the recommended, so even if additional architectures will be built next time, universal will get the auto update priority. In this sense, you'd have to disable auto update anyway. 
Otherwise, it's 60 mb app that gets updates one time in 1-2 months, so free wi-fi seems a friend. And if you need 35 mb strict - take armv7, it will be almost the same. I only separate armv7 because there are actually armv7 phones out there with 300 mb of memory for apps, like some ancient chinaphones or an old Moto E.

I can add arm64 build, but it will only result in three versions which are basically interchangeable on any modern phone, even more questions, and the specific issue with autoupdate eating 30 mb too much traffic won't be ever gone. Taking armv7 version seems like a solution in this case

**Comment by fcore117** [comment]
thermatk: i at least already gone to manual mode now for Telegram, FOSS version is always preferred to me, always. I have used FOSS version many years and continue to do so forever.

**Comment by thermatk** [comment]
New version will have both arm and arm64 as additional smaller options :)
but as always, the fat takes priority
enjoy :partying_face:

**Comment by licaon-kter** [comment]
Fixed for 8.5.2: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10642

Ref: https://gitlab.com/fdroid/fdroiddata/-/issues/2600
